name: Build FreeBSD

on:
  push:
    tags:
      - "v*"

jobs:
  freebsd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: "14.2"
          usesh: true
          run: |
            pkg install -y rust cargo
            cargo build --release

            mkdir release
            cp target/release/speedtest release/

            tar -czf speedtest-freebsd-x86_64.tar.gz -C release speedtest

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: freebsd-package
          path: speedtest-freebsd-x86_64.tar.gz